# configs/finetune_qwen.yml
# Configuration for fine-tuning a Qwen2.5-VL model using Unsloth

model_family: "qwen"
model_id: "unsloth/Qwen2.5-VL-3B-Instruct-bnb-4bit"

# --- Dataset Path ---
# The dataset should be in a conversational format compatible with SFTTrainer
dataset_path: "path/to/your/conversational_dataset"

# --- Training Hyperparameters ---
epochs: 50
batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
warmup_steps: 10

# --- LoRA Parameters ---
load_in_4bit: True
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05

# --- Output ---
output_dir: "training_output/qwen_lucknow_finetune"